Jan-17 10:06:32.243 [main] DEBUG nextflow.cli.Launcher - $> /usr/local/bin/nextflow test.nf
Jan-17 10:06:32.312 [main] INFO  nextflow.cli.CmdRun - N E X T F L O W  ~  version 18.10.1
Jan-17 10:06:32.318 [main] INFO  nextflow.cli.CmdRun - Launching `test.nf` [special_morse] - revision: 90e8bd3fd8
Jan-17 10:06:32.373 [main] DEBUG nextflow.Session - Session uuid: daf94025-909a-4cd5-8358-e04654787173
Jan-17 10:06:32.373 [main] DEBUG nextflow.Session - Run name: special_morse
Jan-17 10:06:32.374 [main] DEBUG nextflow.Session - Executor pool size: 8
Jan-17 10:06:32.381 [main] DEBUG nextflow.cli.CmdRun - 
  Version: 18.10.1 build 5003
  Modified: 24-10-2018 14:03 UTC (16:03 CEST)
  System: Linux 4.15.0-43-generic
  Runtime: Groovy 2.5.3 on OpenJDK 64-Bit Server VM 1.8.0_191-8u191-b12-0ubuntu0.18.04.1-b12
  Encoding: UTF-8 (UTF-8)
  Process: 19621@bose [127.0.1.1]
  CPUs: 8 - Mem: 31.4 GB (13.5 GB) - Swap: 7.9 GB (7.9 GB)
Jan-17 10:06:32.419 [main] DEBUG nextflow.Session - Work-dir: /media/hdd/timothy/quandenser-pipeline/WIP/work [ext2/ext3]
Jan-17 10:06:32.420 [main] DEBUG nextflow.Session - Script base path does not exist or is not a directory: /media/hdd/timothy/quandenser-pipeline/WIP/bin
Jan-17 10:06:32.570 [main] DEBUG nextflow.Session - Session start invoked
Jan-17 10:06:32.575 [main] DEBUG nextflow.processor.TaskDispatcher - Dispatcher > start
Jan-17 10:06:32.575 [main] DEBUG nextflow.script.ScriptRunner - > Script parsing
Jan-17 10:06:32.793 [main] DEBUG nextflow.script.ScriptRunner - > Launching execution
Jan-17 10:06:32.845 [main] DEBUG nextflow.processor.ProcessFactory - << taskConfig executor: null
Jan-17 10:06:32.845 [main] DEBUG nextflow.processor.ProcessFactory - >> processorType: 'local'
Jan-17 10:06:32.848 [main] DEBUG nextflow.executor.Executor - Initializing executor: local
Jan-17 10:06:32.849 [main] INFO  nextflow.executor.Executor - [warm up] executor > local
Jan-17 10:06:32.852 [main] DEBUG n.processor.LocalPollingMonitor - Creating local task monitor for executor 'local' > cpus=8; memory=31.4 GB; capacity=8; pollInterval=100ms; dumpInterval=5m
Jan-17 10:06:32.854 [main] DEBUG nextflow.processor.TaskDispatcher - Starting monitor: LocalPollingMonitor
Jan-17 10:06:32.854 [main] DEBUG n.processor.TaskPollingMonitor - >>> barrier register (monitor: local)
Jan-17 10:06:32.855 [main] DEBUG nextflow.executor.Executor - Invoke register for executor: local
Jan-17 10:06:32.891 [main] DEBUG nextflow.Session - >>> barrier register (process: test)
Jan-17 10:06:32.893 [main] DEBUG nextflow.processor.TaskProcessor - Creating operator > test -- maxForks: 8
Jan-17 10:06:32.911 [main] DEBUG nextflow.script.ScriptRunner - > Await termination 
Jan-17 10:06:32.911 [main] DEBUG nextflow.Session - Session await
Jan-17 10:06:33.066 [Task submitter] DEBUG nextflow.executor.LocalTaskHandler - Launch cmd line: /bin/bash -ue .command.run
Jan-17 10:06:33.069 [Task submitter] INFO  nextflow.Session - [44/160016] Submitted process > test
Jan-17 10:06:33.087 [Task monitor] DEBUG n.processor.TaskPollingMonitor - Task completed > TaskHandler[id: 1; name: test; status: COMPLETED; exit: 1; error: -; workDir: /media/hdd/timothy/quandenser-pipeline/WIP/work/44/160016189b046385d06290eb9b2e65]
Jan-17 10:06:33.102 [Task monitor] ERROR nextflow.processor.TaskProcessor - Error executing process > 'test'

Caused by:
  Process `test` terminated with an error exit status (1)

Command executed:

  cat test.txt
  touch test_dir/test.txt

Command exit status:
  1

Command output:
  test.txt

Command error:
  touch: cannot touch 'test_dir/test.txt': No such file or directory

Work dir:
  /media/hdd/timothy/quandenser-pipeline/WIP/work/44/160016189b046385d06290eb9b2e65

Tip: view the complete command output by changing to the process work dir and entering the command `cat .command.out`
Jan-17 10:06:33.104 [Actor Thread 2] DEBUG nextflow.Session - <<< barrier arrive (process: test)
Jan-17 10:06:33.105 [main] DEBUG nextflow.Session - Session await > all process finished
Jan-17 10:06:33.105 [Task monitor] DEBUG nextflow.Session - Session aborted -- Cause: Process `test` terminated with an error exit status (1)
Jan-17 10:06:33.115 [main] DEBUG nextflow.Session - Session await > all barriers passed
Jan-17 10:06:33.115 [Task monitor] DEBUG n.processor.TaskPollingMonitor - <<< barrier arrives (monitor: local)
Jan-17 10:06:33.118 [main] DEBUG nextflow.trace.StatsObserver - Workflow completed > WorkflowStats[succeedCount=0; failedCount=1; ignoredCount=0; cachedCount=0; succeedDuration=0ms; failedDuration=1ms; cachedDuration=0ms]
Jan-17 10:06:33.137 [main] DEBUG nextflow.CacheDB - Closing CacheDB done
Jan-17 10:06:33.145 [main] DEBUG nextflow.script.ScriptRunner - > Execution complete -- Goodbye
